// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wefjpglykidbgxhgpyjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZmpwZ2x5a2lkYmd4aGdweWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTM5NTQsImV4cCI6MjA2OTAyOTk1NH0.gkHpO6A9qg_0LmmrooePH3BR2bZhESKzESb_Rb8QFaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});